// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASlqmx94ok4n3e_0Zmg6L41HscpM-lovI',
    appId: '1:883547114135:web:1b1d79cd5ea4485521f7d2',
    messagingSenderId: '883547114135',
    projectId: 'mfuguide-backend',
    authDomain: 'mfuguide-backend.firebaseapp.com',
    storageBucket: 'mfuguide-backend.appspot.com',
    measurementId: 'G-8Z0XYSEH66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiPsgZDwEUGfbsNHk7VefA7wf0A27lqvg',
    appId: '1:883547114135:android:6c85cad9d6ae4b1121f7d2',
    messagingSenderId: '883547114135',
    projectId: 'mfuguide-backend',
    storageBucket: 'mfuguide-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVf4Oy8c32IU_BzpeA1claSOUZX6qa_0M',
    appId: '1:883547114135:ios:06097b729049322b21f7d2',
    messagingSenderId: '883547114135',
    projectId: 'mfuguide-backend',
    storageBucket: 'mfuguide-backend.appspot.com',
    iosBundleId: 'com.example.mfuGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVf4Oy8c32IU_BzpeA1claSOUZX6qa_0M',
    appId: '1:883547114135:ios:06097b729049322b21f7d2',
    messagingSenderId: '883547114135',
    projectId: 'mfuguide-backend',
    storageBucket: 'mfuguide-backend.appspot.com',
    iosBundleId: 'com.example.mfuGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASlqmx94ok4n3e_0Zmg6L41HscpM-lovI',
    appId: '1:883547114135:web:a21d3e1a4144742521f7d2',
    messagingSenderId: '883547114135',
    projectId: 'mfuguide-backend',
    authDomain: 'mfuguide-backend.firebaseapp.com',
    storageBucket: 'mfuguide-backend.appspot.com',
    measurementId: 'G-N48SSHL6JJ',
  );
}
